name: .NET

on:
  push:
    branches: [ dev_preview ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs: 
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies, Build and Publish
      run: |
        dotnet publish --configuration Release
    - name: SFTP SSH Action
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        port: 22
        username: pranava
        password: ${{ secrets.PASSWORD }}
        localPath: /home/runner/work/CollegeApp_DotNet/CollegeApp_DotNet/CollegeApp_DotNet/bin/Release/net6.0/publish/
        remotePath: ${{ secrets.REMOTE_TARGET }}
    
