name: .NET

on:
  push:
    branches: [ dev_preview ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs: 
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies, Build and Publish
      run: |
        dotnet publish --configuration Release
    - name: Push to SFTP
  # You may pin to the exact commit or the version.
  # uses: AbleLincoln/push-to-sftp@a6c117bb60fdc94ab8e5b139cdb0b19bea582c81
      uses: AbleLincoln/push-to-sftp@v1.2
      with:
        # SFTP server
        host: 192.168.0.170
        # SFTP server port
        port: 22
        # SFTP username
        username: pranava 
        # SFTP password
        password: 21071998 
        # Source directory to upload from (will upload all files in this directory)
        sourceDir: /home/runner/work/CollegeApp_DotNet/CollegeApp_DotNet/CollegeApp_DotNet/bin/Release/net6.0/publish/
        # Remote directory to upload to (WARNING: overwrites ALL files in this directory)
        targetDir: /var/www/college_app_dotnet
    
    
