name: .NET

on:
  push:
    branches: [ dev_preview ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies, Build and Publish
      run: |
        dotnet restore
        dotnet build --no-restore
        dotnet publish src -c Release -o deploy
    
